# Generated by Django 6.0 on 2025-12-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor'), ('usuario', 'Usuário Comum')], default='Professor', max_length=20),
        ),
    ]
