# Generated by Django 6.0 on 2025-12-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usuario_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('professor', 'professor'), ('aluno', 'aluno')], max_length=20),
        ),
    ]
