# Generated by Django 6.0 on 2025-12-31 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usuario_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='role',
        ),
    ]
