# Generated by Django 6.0 on 2026-01-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_usuario_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('professor', 'professor'), ('aluno', 'aluno')], default='Professor', max_length=20),
            preserve_default=False,
        ),
    ]
