# Generated by Django 6.0 on 2026-01-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usuario_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ano_escolar',
            field=models.CharField(blank=True, choices=[('1_EM', '1º Ano Ensino Médio'), ('2_EM', '2º Ano Ensino Médio'), ('3_EM', '3º Ano Ensino Médio'), ('4_EM', '4º Ano Ensino Médio')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(blank=True, default='foto_perfil/default.png', null=True, upload_to='foto_perfil/'),
        ),
    ]
