# Generated by Django 6.0 on 2026-01-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usuario_ano_escolar_usuario_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='escola',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
