# Generated by Django 6.0 on 2026-01-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='materias/'),
        ),
    ]
