# Generated by Django 6.0 on 2026-01-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0002_alter_material_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='descrica0',
            field=models.TextField(blank=True, null=True),
        ),
    ]
