# Generated by Django 6.0 on 2026-01-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0003_material_descrica0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='descrica0',
            new_name='descricao',
        ),
    ]
